version: "3"
services:
    app:
        image: phlox:latest
        container_name: phlox
        ports:
            - "5000:5000"
        environment:
            - DB_ENCRYPTION_KEY= ${DB_ENCRYPTION_KEY}
            - REACT_APP_BACKEND_URL= # Replace with your desired URL
            - TZ= # Replace with your timezone
        volumes:
            - ./data:/usr/src/app/data # Only for persistent data
            - ./logs:/usr/src/app/logs # Optional: Persist logs
