version: "3"
services:
    app:
        # Use either build or image, but not both. Uncomment the needed line.
        image: localhost/phlox-dev:latest
        #build: .
        container_name: phlox-dev
        network_mode: host
        environment:
            - DB_ENCRYPTION_KEY=${DB_ENCRYPTION_KEY}
            - NODE_ENV=development
            - REACT_APP_BACKEND_URL= # Backend URL
            - TZ=Australia/Melbourne
        volumes:
            - ./server:/usr/src/app/server
            - ./src:/usr/src/app/src
            - ./logs:/usr/src/app/logs
            - ./data:/usr/src/app/data # Only for persistent data
